services:
  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: /bin/sh -c "kong migrations up && kong migrations finish"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
    networks:
      - waini-net
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
