services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN: /run/secrets/cloudflare_tunnel_token
    secrets:
      - cloudflare_tunnel_token
    networks:
      - waini-net
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  cloudflare_tunnel_token:
    file: ./secrets/CLOUDFLARE_TUNNEL_TOKEN